### ISSUE TITLE
JavaScript has classes.

### ISSUE THREAD

**Issue by HarshKapadia2** [tusharnankani/reactive-counter#4]
I noticed a note written in the README.md file that says:

> Note: JavaScript doesn't have simething like classes, like in JAVA.

This statement is wrong, as JavaScript does have classes. [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes) would be a good reference.

**Comment by tusharnankani** [comment]
Fixed.
